### ISSUE TITLE
Boolean values not supported as argument for Spanner

### ISSUE THREAD

**Issue by michael-the-grey** [tcncloud/protoc-gen-persist#50]
The function `ParseValExpr`, does not have a case for booleans and throws the error "unsupported value expression".  Definition found here.

https://github.com/tcncloud/protoc-gen-persist/blob/master/generator/spanner_args.go#L46

Fails on insert
``` SQL
INSERT INTO table_name (table_name_id, bool_field) VALUES(?, true)
```

Also fails on updates
``` SQL
UPDATE table_name set bool_field=true WHERE table_name_id = ?
```

**Comment by iamneal** [comment]
fixed with the new query parser
