### ISSUE TITLE
cockroachdb

### ISSUE THREAD

**Issue by gedw99** [tcncloud/protoc-gen-persist#76]
This is a very cool project. I had been thinking about the same idea of using Protobuf also.

Google SPanner DB is a world wide eventually consistent DB, i was wondering if you were thinking about trying out Cockroachdb which is a golang built DB that has the same aim as Spanner.

https://forum.cockroachlabs.com/t/cockroachdb-vs-google-cloud-spanner/691

also worth reading whats in their V2:
https://www.cockroachlabs.com/blog/cockroachdb-2-0-release/

**Comment by namtzigla** [comment]
Hi,
Thanks for the interest into our project. As far as I know the golang driver for CockroachDB is the pq driver therefore we do support cockroachDB. (all of our sql tests are done using the same driver the only difference is that we use postgres)

The only problems that you might have using this project is that the current state of documentation does not reflect the latest changes that we made on the project and there are couple of bugs that we are fixing right now, but other than that we do support CockroachDB or any other SQL database.

Thanks again for your interest!

**Comment by gedw99** [comment]
Thats great then.

I can try it out without the docs. Its looks pretty obvious just from the
code.

**Comment by namtzigla** [comment]
I'm going to close this due to inactivity
