### ISSUE TITLE
Shallow copied sql client causes transaction to fail

### ISSUE THREAD

**Issue by cGVyc2lzdGVudGx5IGFubm95ZWQ** [tcncloud/protoc-gen-persist#81]
```golang
pl.ServiceGetFoosQuery(db, ...).
	Do(func(row pl.Scanable) error {
		foo, err := pb.FooFromServiceDatabaseRow(row)

		if err != nil {
			return err
		}

		err = pl.ServiceCreateBarQuery(tx, ...).
			Do(func(row pl.Scanable) error { ... })

		if err != nil {
			return err
		}

		err = pl.ServiceCreateBazQuery(tx, ...).
			Do(func(row pl.Scanable) error { ... })

		if err != nil {
			return err
		}

		...
	})
```

Yields the error pq: unexpected Parse response 'D'

Doing the same control flow directly with the sql client and without persist works. It looks like the following assignments shallow copy the sql client which is not safe to do. 

https://github.com/tcncloud/protoc-gen-persist/blob/1ba7f5f8395d22ce70e6d28d80ffe5fa79f5ee56/generator/persist_lib_stringer.go#L93
https://github.com/tcncloud/protoc-gen-persist/blob/1ba7f5f8395d22ce70e6d28d80ffe5fa79f5ee56/generator/persist_lib_stringer.go#L169
https://github.com/tcncloud/protoc-gen-persist/blob/1ba7f5f8395d22ce70e6d28d80ffe5fa79f5ee56/generator/persist_lib_stringer.go#L187

**Comment by iamneal** [comment]
Thanks, I will get working on a fix

**Comment by iamneal** [comment]
this fix is in master
